"""initial schema

Revision ID: 955edbb08506
Revises: 
Create Date: 2026-09-01 22:01:12.673981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955edbb08506'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_table('screening_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('candidate_id', sa.String(length=256), nullable=False),
    sa.Column('role_type', sa.String(length=128), nullable=True),
    sa.Column('role_seniority', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=256), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ensemble_runs', sa.Integer(), nullable=False),
    sa.Column('cv_text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_screening_runs_batch_id', 'screening_runs', ['batch_id'], unique=False)
    op.create_index('ix_screening_runs_created_at', 'screening_runs', ['created_at'], unique=False)
    op.create_index('ix_screening_runs_tenant_id', 'screening_runs', ['tenant_id'], unique=False)
    op.create_table('evidence_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=4), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('is_contradiction', sa.Boolean(), nullable=False),
    sa.Column('is_silence_flag', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_claims_run_id', 'evidence_claims', ['run_id'], unique=False)
    op.create_table('hire_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('hired', sa.Boolean(), nullable=False),
    sa.Column('performance_90d', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('human_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('original_verdict', sa.String(length=32), nullable=False),
    sa.Column('override_verdict', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('trajectory_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trajectory_entries_run_id', 'trajectory_entries', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trajectory_entries_run_id', table_name='trajectory_entries')
    op.drop_table('trajectory_entries')
    op.drop_table('human_overrides')
    op.drop_table('hire_outcomes')
    op.drop_index('ix_evidence_claims_run_id', table_name='evidence_claims')
    op.drop_table('evidence_claims')
    op.drop_index('ix_screening_runs_tenant_id', table_name='screening_runs')
    op.drop_index('ix_screening_runs_created_at', table_name='screening_runs')
    op.drop_index('ix_screening_runs_batch_id', table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
